-- MySQL Script generated by MySQL Workbench
-- 11/10/16 19:52:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarjeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tarjeta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tarjeta` (
  `ntarjeta` DECIMAL(10) NOT NULL,
  `npuntos` DECIMAL(10000) NOT NULL,
  `Usuarios_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ntarjeta`, `Usuarios_dni`),
  INDEX `fk_Tarjeta_Usuarios1_idx` (`Usuarios_dni` ASC),
  CONSTRAINT `fk_Tarjeta_Usuarios1`
    FOREIGN KEY (`Usuarios_dni`)
    REFERENCES `mydb`.`Usuarios` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tienda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tienda` (
  `cif` VARCHAR(9) NOT NULL,
  `ntienda` VARCHAR(45) NOT NULL,
  `dtienda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Compra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `idCompra` INT NOT NULL,
  `Tienda_cif` VARCHAR(9) NOT NULL,
  `Tarjeta_ntarjeta` DECIMAL(10) NOT NULL,
  `Tarjeta_Usuarios_dni` VARCHAR(9) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME(10) NOT NULL,
  `importe` DOUBLE NOT NULL,
  PRIMARY KEY (`idCompra`, `Tienda_cif`),
  INDEX `fk_Compra_Tienda1_idx` (`Tienda_cif` ASC),
  INDEX `fk_Compra_Tarjeta1_idx` (`Tarjeta_ntarjeta` ASC, `Tarjeta_Usuarios_dni` ASC),
  CONSTRAINT `fk_Compra_Tienda1`
    FOREIGN KEY (`Tienda_cif`)
    REFERENCES `mydb`.`Tienda` (`cif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Tarjeta1`
    FOREIGN KEY (`Tarjeta_ntarjeta` , `Tarjeta_Usuarios_dni`)
    REFERENCES `mydb`.`Tarjeta` (`ntarjeta` , `Usuarios_dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Premio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Premio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Premio` (
  `idPremio` INT NOT NULL,
  `concepto` VARCHAR(90) NOT NULL,
  `coste` DOUBLE NOT NULL,
  PRIMARY KEY (`idPremio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Canjeo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Canjeo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Canjeo` (
  `idCanjeo` INT NOT NULL,
  `Tarjeta_ntarjeta` DECIMAL(10) NOT NULL,
  `Tarjeta_Usuarios_dni` VARCHAR(9) NOT NULL,
  `Premio_idPremio` INT NOT NULL,
  PRIMARY KEY (`idCanjeo`, `Tarjeta_ntarjeta`, `Tarjeta_Usuarios_dni`, `Premio_idPremio`),
  INDEX `fk_Canjeo_Tarjeta1_idx` (`Tarjeta_ntarjeta` ASC, `Tarjeta_Usuarios_dni` ASC),
  INDEX `fk_Canjeo_Premio1_idx` (`Premio_idPremio` ASC),
  CONSTRAINT `fk_Canjeo_Tarjeta1`
    FOREIGN KEY (`Tarjeta_ntarjeta` , `Tarjeta_Usuarios_dni`)
    REFERENCES `mydb`.`Tarjeta` (`ntarjeta` , `Usuarios_dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Canjeo_Premio1`
    FOREIGN KEY (`Premio_idPremio`)
    REFERENCES `mydb`.`Premio` (`idPremio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
